name: Create Release ZIP
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip Folder
        run: zip -r ModernClock.zip . -x "*.git*"

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: ModernClock.zip